### ISSUE TITLE
Doc: joining geocoding results back to input data 

### ISSUE THREAD

**Issue by JosiahParry** [R-ArcGIS/arcgisgeocode#14]
Prompted from @mixedlogit where they are using `find_address_candidate()` to do single address geocoding. The result includes an `input_id`. Here we need to illustrate how to join that back to the original input data. 

This would be a good "tutorial" 

CC @mmachir as we should probably have this on the doc site.

**Comment by JosiahParry** [comment]
Alternatively we figure out a way to return an empty row from the geocoder but thats actually a lot more work than i think is worth it. We should have a tutorial on this and the doc page should make this very clear.


repro:

```r
add <- readr::read_csv("https://github.com/R-ArcGIS/arcgisgeocode/files/15124731/data.csv")

single_line <- add$end

res <- find_address_candidates(single_line, max_locations = 1)

res[,"input_id"]
```

**Comment by JosiahParry** [comment]
To do the joining: 

```r

add <- readr::read_csv("https://github.com/R-ArcGIS/arcgisgeocode/files/15124731/data.csv") |> 
  dplyr::mutate(
    input_id = dplyr::row_number()
  )

# geocode
res <- find_address_candidates(single_line, max_locations = 1)

# join back
dplyr::left_join(add, res[, "input_id"])
```

**Comment by mmachir** [comment]
yes! great. I already added this to the tutorial/blog I have drafted for batch geocoding but could add in an example for `find_address_locations()` too - or just mention that the same method can be used for each? (just joining on input_id instead of result_id?)
